version: "3.9"

services:
  app:
    image: elixir:1.17
    working_dir: /app
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/apps/ui/assets/node_modules
    ports:
      - "4000:4000"
    command: >
      bash -lc "apt-get update && apt-get install -y --no-install-recommends curl ca-certificates gnupg && \
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs && \
      mix local.hex --force && mix local.rebar --force && mix deps.get && \
      cd apps/ui/assets && npm install && npm run build && cd - && \
      mix phx.server"
    restart: unless-stopped
