version: "3.9"

services:
  app:
    image: elixir:1.17
    working_dir: /app
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    command: >
      bash -lc "mix local.hex --force && mix local.rebar --force && mix deps.get && mix phx.server"
    restart: unless-stopped
    depends_on:
      - assets

  assets:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/apps/ui/assets/node_modules
    command: >
      bash -lc "cd apps/ui/assets && npm install && npm run build"
